name: Hongzhi.tian CI

on:
  # push操作触发
  push:
    branches: [ "dev" ]
  # pr操作触发
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Docker 构建镜像和发布镜像
      - name: Docker Build and Push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker buildx build \
            --platform=linux/amd64 \
            --file ./Dockerfile . \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME}}:0.0.1
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME}}:0.0.1

      # 连接 ssh 执行启动服务的脚本
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JINLING_HOST }}
          username: ${{ secrets.JINLING_PASSWORD }}
          password: ${{ secrets.JINLING_USERNAME }}
          script: |
          	# 此脚本是放到服务器自定义的目录上，此处写你脚本对应的路径就可以了
            sh /root/docker/lianjia/start-jinling.sh
